# Generated by Django 4.1 on 2022-08-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="git_address",
            field=models.CharField(
                default="", max_length=200, null=True, verbose_name="git项目地址"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="git_name",
            field=models.CharField(
                default="", max_length=50, null=True, verbose_name="git项目名称"
            ),
        ),
    ]
