# Generated by Django 4.1 on 2022-09-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_git_address_project_git_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_clone",
            field=models.IntegerField(default=0, verbose_name="是否克隆"),
        ),
        migrations.AddField(
            model_name="project",
            name="test_num",
            field=models.IntegerField(default=0, verbose_name="文件数"),
        ),
    ]
