# Generated by Django 4.1 on 2022-08-20 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_project_git_address_project_git_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(default="", max_length=200, verbose_name="文件名"),
                ),
                (
                    "class_name",
                    models.CharField(default="", max_length=100, verbose_name="类名"),
                ),
                (
                    "class_doc",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="类描述"
                    ),
                ),
                (
                    "case_name",
                    models.CharField(default="", max_length=100, verbose_name="方法名"),
                ),
                (
                    "case_doc",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="方法描述"
                    ),
                ),
                (
                    "report",
                    models.TextField(default="", null=True, verbose_name="报告内容"),
                ),
                ("status", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "result",
                    models.CharField(
                        default="", max_length=50, null=True, verbose_name="结果"
                    ),
                ),
                (
                    "system_out",
                    models.TextField(default="", null=True, verbose_name="日志"),
                ),
                ("error", models.TextField(default="", null=True, verbose_name="错误信息")),
                ("run_time", models.FloatField(default=0, verbose_name="运行时长")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
