# Generated by Django 4.1 on 2022-09-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="error",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="report",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="result",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="system_out",
        ),
    ]
