# Generated by Django 4.1 on 2022-09-12 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_remove_testcase_error_remove_testcase_report_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="名称"),
                ),
                (
                    "report",
                    models.TextField(default="", null=True, verbose_name="报告内容"),
                ),
                ("passed", models.IntegerField(default=0, verbose_name="通过用例")),
                ("error", models.IntegerField(default=0, verbose_name="错误用例")),
                ("failure", models.IntegerField(default=0, verbose_name="失败用例")),
                ("skipped", models.IntegerField(default=0, verbose_name="跳过用例")),
                ("tests", models.IntegerField(default=0, verbose_name="总用例数")),
                (
                    "system_out",
                    models.TextField(default="", null=True, verbose_name="日志"),
                ),
                ("run_time", models.FloatField(default=0, verbose_name="运行时长")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.testcase"
                    ),
                ),
            ],
        ),
    ]
